### ISSUE TITLE
menu does not look correct

### ISSUE THREAD

**Issue by willral** [B00merang-Project/Windows-Vista#1]
i have a slight problem with the menu, none of the buttons look correct and has defaulted back to the cinnamon look. running on gtk 3.22 linux mint

**Comment by Elbullazul** [comment]
can you upload a screenshot of the issue?

**Comment by willral** [comment]
[https://imgur.com/0Oqb6ez](url)

**Comment by Elbullazul** [comment]
you'd need a menu applet to make it look like the windows menu.

normally, I'd recommend using [CinnVII](https://cinnamon-spices.linuxmint.com/applets/view/281) but it doesn't seem to work on cinnamon 20

**Comment by willral** [comment]
thanks CinnVII works just fine

**Comment by Elbullazul** [comment]
does it fix the issue?

**Comment by willral** [comment]
yes it does
