### ISSUE TITLE
Issues with xfce 4

### ISSUE THREAD

**Issue by DennisAnabones** [B00merang-Project/Windows-Vista#4]
this theme doesnt work properly even after reboot
![Screenshot_2023-03-22_16-40-49](https://user-images.githubusercontent.com/82602747/226958378-396d64e4-302b-4132-8cce-d1eaf7cd54a6.png)

**Comment by Elbullazul** [comment]
try opening the theme folder, deleting the gtk-3.0 folder and renaming the existing gtk-3.20 folder to gtk-3.0

**Comment by DennisAnabones** [comment]
it works
but how do I get the vista taskbar?
